# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: David Gentile | Web Developer
email: davidgentile@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal and portfolio website for David Gentile, Web Developer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://davidgentile.net" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dfgentile
github_username:  diva-D

# Build settings
markdown: kramdown
theme: 
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
minimal_mistakes_skin: "contrast" # "air", "aqua", "contrast", "dark", "default", "dirt", "neon", "mint", "plum" "sunrise"
paginate: 5 # amount of posts to show
paginate_path: _pages/blog/page:num
include: ["_pages"]

author:
  name   : "David Gentile"
  avatar : "/assets/images/david-gentile-headshot.1.jpeg"
  bio    : "My awesome biography constrained to a sentence or two goes here."
  email  : # optional
  uri    : "http://davidgentile.net"
  home   : # null (default), "absolute or relative url to link to author home"
  github : "diva-D"
  twitter: "dfgentile"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

comments:
  provider: "disqus"
  disqus:
    shortname: "davidgentile"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
