baseURL: "https://davidgentile.net"
languageCode: "en-us"
title: "David Gentile"
theme: "PaperMod"
params:
  homeInfoParams:
    Title: "Developer & AI Accelerant"
    Content: >
      Python, JavaScript, and Google Apps Script developer.

      - Building [PromptList.io](https://promptlist.io), curated prompts for AI tools like ChatGPT.

  socialIcons: # optional
    - name: "Twitter"
      url: "https://twitter.com/dfgentile"

    - name: "Github"
      url: "https://www.github.com/diva-D"
